/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Plum: typeof import('./src/components/Plum/Plum.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheBanner: typeof import('./src/components/Banner/TheBanner.vue')['default']
    TheTopNav: typeof import('./src/components/TopNav/TheTopNav.vue')['default']
    TheTopNavCenter: typeof import('./src/components/TopNav/TheTopNavCenter.vue')['default']
    TheTopNavLeft: typeof import('./src/components/TopNav/TheTopNavLeft.vue')['default']
    TheTopNavRight: typeof import('./src/components/TopNav/TheTopNavRight.vue')['default']
  }
}
