/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheBanner: typeof import('./src/components/Banner/TheBanner.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheTopNav: typeof import('./src/components/TopNav/TheTopNav.vue')['default']
    TheTopNavCenter: typeof import('./src/components/TopNav/TheTopNavCenter.vue')['default']
    TheTopNavLeft: typeof import('./src/components/TopNav/TheTopNavLeft.vue')['default']
    TheTopNavRight: typeof import('./src/components/TopNav/TheTopNavRight.vue')['default']
  }
}
